name: commit test

on:
  push:
    branches: [commit-test]

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # may be required to allow to push commits
    steps:
      - uses: actions/checkout@v4
      - name: Setup GitHut actions bot identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: first commit attempt, with no changes
        run: |
          git add valid_proxies.txt
          # Only try to push if there are changes, i.e., if the commit is successful
          if git commit -m'updating valid_proxies.txt'; then git push; fi
      - name: modify valid_proxies
        run: echo asdf >> valid_proxies.txt
      - name: second commit attempt, with changes
        run: |
          git add valid_proxies.txt
          # Only try to push if there are changes, i.e., if the commit is successful
          if git commit -m'updating valid_proxies.txt'; then git push; fi
